### ISSUE TITLE
>1k FFT size support

### ISSUE THREAD

**Issue by micooke** [rox906/tcFFT#1]
Would you please be able to flesh out the radices and mergings for 2k and above FFT sizes. Or if you have a reference, I could do it and send off a PR?
Cheers :+1:

**Comment by rox906** [comment]
Sorry for the late reply. This project is based on my paper on CLUSTER 2021 and I'm preparing the presentation recently. The paper will be available after 9.9 and I will then add a reference to this project. Before that, you can try to develop it according to the layer_1024_0 function. As 1024=16\*16\*4 and 2048=16\*16\*8 (or 4\*2), 16 processes with tensor cores and others with CUDA cores.

**Comment by micooke** [comment]
No worries, I'll have a look!

**Comment by rox906** [comment]
The paper can be found here https://ieeexplore.ieee.org/document/9555937.
